// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjmpzkjjlgvtbiycajja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbXB6a2pqbGd2dGJpeWNhamphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTYyMzIsImV4cCI6MjA2MzU5MjIzMn0.keZoFjaPFtj8aMjZJ32WGSkfBQw8O3FZTN5GwkbFgkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);